Basic:
  Mah:
    BotNum: 12345678
    Http: http://localhost:8080
    VerifyKey: 'password'
    WebSocker: http://localhost:8080
  Master: 12345678
  PATH: /root/eliot/
  #eg PATH: /root/eliot/
Saya:
  APEX_CHECK:
    API: api_key
  Tracemoe:
    API: api_key
  Translate:
    APP_CHAIN: api_key
    APP_ID: api_id
  Weather:
    KEY: api_key
    URL_CITY_ID: https://geoapi.qweather.com/v2/city/lookup?
    URL_WEATHER_3D: https://devapi.qweather.com/v7/weather/3d?
  api_a60_pic:
    Interval: 20
    #撤回时间
    Recall: false
    #是否撤回
    san: r16

Final: false