Basic:
  Mah:
    BotNum: 2055863802
    Http: http://localhost:8080
    VerifyKey: '36041322107'
    WebSocker: http://localhost:8080
  Master: 1250934898
  PATH: /root/Eliot/
Final: true
Saya:
  APEX_CHECK:
    API: 5dc1a6f3b6955edb84d5f58b62ce9552
  Tracemoe:
    API: api_key
  Translate:
    APP_CHAIN: m3C3NIkTYhqwT1CngCwu
    APP_ID: 20230116001532219
  Weather:
    KEY: 57e796faa5a546e98205072c2c336ff3
    URL_WEATHER_3D: https://devapi.qweather.com/v7/weather/3d?
  api_a60_pic:
    Interval: 20
    Recall: false
    san: r16
